version: '3'

tasks:
  compile:
    cmds:
      - go build -o bin/server cmd/server/main.go

  build-image:
    cmds:
      - docker build -t bookstore .
  start:
    cmds:
      - docker-compose up --detach
  run:
    cmds:
      - docker-compose up
  stop:
    cmds:
      - docker-compose down